function submitForm() {
    const name = document.getElementById("name").value;
    const surname = document.getElementById("surname").value;
    const phoneNumber = document.getElementById("phoneNumber").value;
    const email = document.getElementById("email").value;
    const id = document.getElementById("id").value;
    const qualification = document.getElementById("qualification").value;
    const skills = document.getElementById("skills").value;
    const website = document.getElementById("website").value;
    const address = document.getElementById("address").value;
    const gender = document.getElementById("gender").value;
    const marital = document.getElementById("marital").value;
    const grade = document.getElementById("grade").value;
    const education = document.getElementById("education").value;
    const skill1 = document.getElementById("skill1").value;
    const skill2 = document.getElementById("skill2").value;
    const skill3 = document.getElementById("skill3").value;
    const skill4 = document.getElementById("skill4").value;
    const skill5 = document.getElementById("skill5").value;
    const skill6 = document.getElementById("skill6").value;
    const skill7 = document.getElementById("skill7").value;
    const skill8 = document.getElementById("skill8").value;
    const experience1 = document.getElementById("experience1").value;
    const experience2 = document.getElementById("experience2").value;
    const experience3 = document.getElementById("experience3").value;
    const experience4 = document.getElementById("experience4").value;
    const experience5 = document.getElementById("experience5").value;
    const experience6 = document.getElementById("experience6").value;
    const objectives = document.getElementById("objectives").value;
    const course = document.getElementById("course").value;
    const language = document.getElementById("language").value;
    const awards = document.getElementById("awards").value;
    const refferences = document.getElementById("refferences").value;
    const contactName = document.getElementById("contactName").value;
    const relationship = document.getElementById("relationship").value;
    const contactNumber = document.getElementById("contactNumber").value;
    const hobbies = document.getElementById("hobbies").value;

    localStorage.setItem('name', name);
    localStorage.setItem('surname', surname);
    localStorage.setItem('phoneNumber', phoneNumber);
    localStorage.setItem('email', email);
    localStorage.setItem('id', id);
    localStorage.setItem('qualification', qualification);
    localStorage.setItem('skills', skills);
    localStorage.setItem('website', website);
    localStorage.setItem('address', address);
    localStorage.setItem('gender', gender);
    localStorage.setItem('marital', marital);
    localStorage.setItem('grade', grade);
    localStorage.setItem('education', education);
    localStorage.setItem('skill1', skill1);
    localStorage.setItem('skill2', skill2);
    localStorage.setItem('skill3', skill3);
    localStorage.setItem('skill4', skill4);
    localStorage.setItem('skill5', skill5);
    localStorage.setItem('skill6', skill6);
    localStorage.setItem('skill7', skill7);
    localStorage.setItem('skill8', skill8);
    localStorage.setItem('experience1', experience1);
    localStorage.setItem('experience2', experience2);
    localStorage.setItem('experience3', experience3);
    localStorage.setItem('experience4', experience4);
    localStorage.setItem('experience5', experience5);
    localStorage.setItem('experience6', experience6);
	
    localStorage.setItem('objectives', objectives);
    localStorage.setItem('course', course);
    localStorage.setItem('language', language);
    localStorage.setItem('awards', awards);
    localStorage.setItem('refferences', refferences);
    localStorage.setItem('contactName', contactName);
    localStorage.setItem('relationship', relationship);
    localStorage.setItem('contactNumber', contactNumber);
    localStorage.setItem('hobbies', hobbies);
	
	window.location.href = 'cv1.html';
}

function submitForm2(){
    const name = document.getElementById("name").value;
    const surname = document.getElementById("surname").value;
    const phoneNumber = document.getElementById("phoneNumber").value;
    const email = document.getElementById("email").value;
    const id = document.getElementById("id").value;
    const qualification = document.getElementById("qualification").value;
    const skills = document.getElementById("skills").value;
    const website = document.getElementById("website").value;
    const address = document.getElementById("address").value;
    const gender = document.getElementById("gender").value;
    const marital = document.getElementById("marital").value;
    const grade = document.getElementById("grade").value;
    const education = document.getElementById("education").value;
    const skill1 = document.getElementById("skill1").value;
    const skill2 = document.getElementById("skill2").value;
    const skill3 = document.getElementById("skill3").value;
    const skill4 = document.getElementById("skill4").value;
    const skill5 = document.getElementById("skill5").value;
    const skill6 = document.getElementById("skill6").value;
    const skill7 = document.getElementById("skill7").value;
    const skill8 = document.getElementById("skill8").value;
    const experience1 = document.getElementById("experience1").value;
    const experience2 = document.getElementById("experience2").value;
    const experience3 = document.getElementById("experience3").value;
    const experience4 = document.getElementById("experience4").value;
    const experience5 = document.getElementById("experience5").value;
    const experience6 = document.getElementById("experience6").value;
	
    const objectives = document.getElementById("objectives").value;
    const course = document.getElementById("course").value;
    const language = document.getElementById("language").value;
    const awards = document.getElementById("awards").value;
    const refferences = document.getElementById("refferences").value;
    const contactName = document.getElementById("contactName").value;
    const relationship = document.getElementById("relationship").value;
    const contactNumber = document.getElementById("contactNumber").value;
    const hobbies = document.getElementById("hobbies").value;

    localStorage.setItem('name', name);
    localStorage.setItem('surname', surname);
    localStorage.setItem('phoneNumber', phoneNumber);
    localStorage.setItem('email', email);
    localStorage.setItem('id', id);
    localStorage.setItem('qualification', qualification);
    localStorage.setItem('skills', skills);
    localStorage.setItem('website', website);
    localStorage.setItem('address', address);
    localStorage.setItem('gender', gender);
    localStorage.setItem('marital', marital);
    localStorage.setItem('grade', grade);
    localStorage.setItem('education', education);
    localStorage.setItem('skill1', skill1);
    localStorage.setItem('skill2', skill2);
    localStorage.setItem('skill3', skill3);
    localStorage.setItem('skill4', skill4);
    localStorage.setItem('skill5', skill5);
    localStorage.setItem('skill6', skill6);
    localStorage.setItem('skill7', skill7);
    localStorage.setItem('skill8', skill8);
    localStorage.setItem('experience1', experience1);
    localStorage.setItem('experience2', experience2);
    localStorage.setItem('experience3', experience3);
    localStorage.setItem('experience4', experience4);
    localStorage.setItem('experience5', experience5);
    localStorage.setItem('experience6', experience6);
	
    localStorage.setItem('objectives', objectives);
    localStorage.setItem('course', course);
    localStorage.setItem('language', language);
    localStorage.setItem('awards', awards);
    localStorage.setItem('refferences', refferences);
    localStorage.setItem('contactName', contactName);
    localStorage.setItem('relationship', relationship);
    localStorage.setItem('contactNumber', contactNumber);
    localStorage.setItem('hobbies', hobbies);
	
	window.location.href = 'cv2.html';
}


function submitForm3() {
    const name = document.getElementById("name").value;
    const surname = document.getElementById("surname").value;
    const phoneNumber = document.getElementById("phoneNumber").value;
    const email = document.getElementById("email").value;
    const id = document.getElementById("id").value;
    const qualification = document.getElementById("qualification").value;
    const skills = document.getElementById("skills").value;
    const website = document.getElementById("website").value;
    const address = document.getElementById("address").value;
    const gender = document.getElementById("gender").value;
    const marital = document.getElementById("marital").value;
    const grade = document.getElementById("grade").value;
    const education = document.getElementById("education").value;
    const skill1 = document.getElementById("skill1").value;
    const skill2 = document.getElementById("skill2").value;
    const skill3 = document.getElementById("skill3").value;
    const skill4 = document.getElementById("skill4").value;
    const skill5 = document.getElementById("skill5").value;
    const skill6 = document.getElementById("skill6").value;
    const skill7 = document.getElementById("skill7").value;
    const skill8 = document.getElementById("skill8").value;
    const experience1 = document.getElementById("experience1").value;
    const experience2 = document.getElementById("experience2").value;
    const experience3 = document.getElementById("experience3").value;
    const experience4 = document.getElementById("experience4").value;
    const experience5 = document.getElementById("experience5").value;
    const experience6 = document.getElementById("experience6").value;
	
    const objectives = document.getElementById("objectives").value;
    const course = document.getElementById("course").value;
    const language = document.getElementById("language").value;
    const awards = document.getElementById("awards").value;
    const refferences = document.getElementById("refferences").value;
    const contactName = document.getElementById("contactName").value;
    const relationship = document.getElementById("relationship").value;
    const contactNumber = document.getElementById("contactNumber").value;
    const hobbies = document.getElementById("hobbies").value;

    localStorage.setItem('name', name);
    localStorage.setItem('surname', surname);
    localStorage.setItem('phoneNumber', phoneNumber);
    localStorage.setItem('email', email);
    localStorage.setItem('id', id);
    localStorage.setItem('qualification', qualification);
    localStorage.setItem('skills', skills);
    localStorage.setItem('website', website);
    localStorage.setItem('address', address);
    localStorage.setItem('gender', gender);
    localStorage.setItem('marital', marital);
    localStorage.setItem('grade', grade);
    localStorage.setItem('education', education);
    localStorage.setItem('skill1', skill1);
    localStorage.setItem('skill2', skill2);
    localStorage.setItem('skill3', skill3);
    localStorage.setItem('skill4', skill4);
    localStorage.setItem('skill5', skill5);
    localStorage.setItem('skill6', skill6);
    localStorage.setItem('skill7', skill7);
    localStorage.setItem('skill8', skill8);
    localStorage.setItem('experience1', experience1);
    localStorage.setItem('experience2', experience2);
    localStorage.setItem('experience3', experience3);
    localStorage.setItem('experience4', experience4);
    localStorage.setItem('experience5', experience5);
    localStorage.setItem('experience6', experience6);
	
    localStorage.setItem('objectives', objectives);
    localStorage.setItem('course', course);
    localStorage.setItem('language', language);
    localStorage.setItem('awards', awards);
    localStorage.setItem('refferences', refferences);
    localStorage.setItem('contactName', contactName);
    localStorage.setItem('relationship', relationship);
    localStorage.setItem('contactNumber', contactNumber);
    localStorage.setItem('hobbies', hobbies);
	
	window.location.href = 'cv3.html';
}